### ISSUE TITLE
New request: wikileaks.org

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#1022] opened 2024-06-02 11:35 UTC
- Website URL: https://wikileaks.org/
- License: No License
- Desired ZIM Title: wikileaks.org
- Desired ZIM Description: 
- Desired ZIM Icon –png (URL or attach one): 
![image](https://github.com/openzim/zim-requests/assets/62152714/cc42a5be-ca92-471b-ac8e-24b0150f009c)
- Language (ISO 639-3): **en**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment] 2024-07-22 23:14
@Popolechien couldn't find license disclaimer 
Shall we consider it free?

**Comment by benoit74** [comment] 2024-07-23 06:12
> WikiLeaks specializes in the analysis and publication of large datasets of censored or otherwise restricted official materials involving war, spying and corruption. It has so far published more than 10 million documents and associated analyses.

Of course it is **NOT** really free content. It is a collection of censored and restricted official materials. As Rexadev said, there is intentionally no license associated with this content, because Wikileaks as an organization don't give a shit and promotes freedom of knowledge and speech. And they have no copyright on most published material (besides their analyses). Whether we also don't give a shit is another question which need to be answered by the association. 

You need to be aware that this website is going to be hard to scrape with zimit (some interesting content, e.g. "Macron emails" is behind search forms, some content is stored on external domains, e.g. Collateral Murder, Iraq war logs, ...). If we decide to create ZIM for it, I think we should consider this as a project, and create one ZIM per leak, especially since each leak is usually quite big in terms of MB/GB.

**Comment by Popolechien** [comment] 2024-07-23 07:30
I would consider it it's own project, and seeing how much they have turned into a Russian asset / manipulation tool (e.g. fake Macron emails, or Syrian war crimes denial) I would rather have a long, serious internal discussion about what we choose to reproduce. And then there's the legal liability, donor issues, etc.

We've got enough on our plate atm so I'll close the issue as not planned.

**Closed by Popolechien** 2024-07-23 07:30 UTC
Labels: Zimit

**Comment by benoit74** [comment] 2024-07-23 07:36
> We've got enough on our plate atm so I'll close the issue as not planned.

I don't think this is an acceptable reason to close an issue. But I agree that we can close the issue for all the other reasons you've given.
