### ISSUE TITLE
New request: marxists.org

### ISSUE THREAD

**Issue by adrsch** [openzim/zim-requests#1037] opened 2024-06-11 04:07 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://marxists.org
- License: Creative Commons
- Desired ZIM Title: Marxists Internet Archive
- Desired ZIM Description: The Marxists Internet Archive is an all-volunteer, non-profit public library
- Desired ZIM Icon –ico https://www.marxists.org/favicon.ico
- Language (ISO 639-3): eng
- Is this a MediaWiki?: no

**Comment by Popolechien** [comment] 2024-06-11 06:22
Duplicate of #311 and #594. We already got the German and Spanish versions, some bugfix required for the other languages.

**Closed by Popolechien** 2024-06-11 06:22 UTC
Labels: Duplicate
