### ISSUE TITLE
PFAF is taking so long scraping and not finishing

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zim-requests#1009] opened 2023-12-05 08:37 UTC
Hi, this recipe [here](https://farm.openzim.org/pipeline/dc09425d-c2d6-4f6a-9503-c0ae74236402) is taking very long time scraping and couple of times it reaches 89% and stops.
Please check

**Comment by benoit74** [comment] 2024-05-28 12:09
Transferring to zim-requests since this is not a new scraper problem and should be tracked by content team now.
I just requested the task again with upcoming zimit2 to check what is going on.

**Comment by benoit74** [comment] 2024-05-28 12:09
Indeed it's a duplicate of https://github.com/openzim/zim-requests/issues/745, let's close this one.

**Closed by benoit74** 2024-05-28 12:09 UTC
Labels: Upstream
