### ISSUE TITLE
wiki.nixos.org

### ISSUE THREAD

**Issue by jonahaberle** [openzim/zim-requests#1200] opened 2024-10-31 21:47 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://wiki.nixos.org/wiki/NixOS_Wiki
- Daily XML dump: https://wiki.nixos.org/wikidump.xml.zst
- License: MIT License
- Desired ZIM Title: **NixOS Wiki**
- Desired ZIM Description: **The NixOS Wiki is a community-run documentation resource for NixOS users.**
- Desired ZIM Icon –png (URL or attach one): https://wiki.nixos.org/nixos.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by benoit74** [comment] 2024-11-01 08:15
Duplicate of https://github.com/openzim/zim-requests/issues/1030 (I've just added the dump to this issue)

**Closed by benoit74** 2024-11-01 08:15 UTC
