### ISSUE TITLE
[Recipe created] learn.microsoft.com

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#650] opened 2023-05-17 05:17 UTC
- Website URL: https://learn.microsoft.com
- License: `https://learn.microsoft.com/en-us/legal/termsofuse#personal-and-non-commercial-use-limitation Unless otherwise specified, the Services are for your personal and non-commercial use. You may not modify, copy, distribute, transmit, publicly display, perform, reproduce, publish, license, create derivative works from, transfer or sell any information, software, products or services obtained from the Services (except for your own, personal, non-commercial use) without prior written consent from Microsoft.`
- Desired ZIM Title: **Microsoft Learn**
- Desired ZIM Description: **Short description**
- Desired ZIM Icon –png (URL or attach one): https://en.wikipedia.org/wiki/Microsoft#/media/File:Microsoft_logo_(2012).svg
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Rexadev** [comment] 2023-06-15 09:40
@RavanJAltaie ping

**Comment by Rexadev** [comment] 2023-09-19 10:46
@RavanJAltaie Updates ?

**Comment by Rexadev** [comment] 2024-03-04 08:22
@RavanJAltaie Updates ?

**Comment by RavanJAltaie** [comment] 2024-05-19 23:46
Recipe created
https://farm.openzim.org/recipes/learn.microsoft.com_en_all
I'll update the library linke once ready

**Comment by benoit74** [comment] 2024-06-20 08:17
After 10 days processing, stats are `7% (114967 / 1550897)`. More than one million is not possible, this means the ZIM will be huge / it will take forever to complete the task.

I suggest to stop the task. @RavanJAltaie could you do that if you agree?

Having a brief look at https://learn.microsoft.com/, it is clearly not feasible to create one ZIM for the whole website. There is documentation about all Microsoft product on this website: https://learn.microsoft.com/en-us/docs/

And some product like Azure are even huge and have many sub-products: https://learn.microsoft.com/en-us/azure/?product=popular

We need to decide on a much finer strategy to ZIM this website. Maybe one ZIM per product would work, maybe even one per subproducts for huge ones like Azure.

**Comment by Popolechien** [comment] 2024-06-20 08:31
> Maybe one ZIM per product would work, maybe even one per subproducts for huge ones like Azure.

This seems to be the way, yes, but a million pages seems yuge. Is this for English only, or was this going to be another `mul` zim ?

**Comment by Jaifroid** [comment] 2024-06-20 09:42
Could I just point out that the terms of the licence quoted in the first post are extremely clear, viz. "You may not **modify**, **copy**, **distribute**, transmit, **publicly display**, perform, **reproduce**, **publish**, license, create derivative works from, transfer or sell any information, software, products or services obtained from the Services (except for your own, personal, non-commercial use) without prior written consent from Microsoft".

I'm sorry to put a dampener on things, but how is making a ZIM of this content (copying, reproducing, arguably transforming and creating a derivative work) and putting that ZIM on a download site owned by Association Kiwix (distributing, transmitting, publishing in a non-personal capacity) not a violation of the licence? It doesn't say you may copy and republish so long as it is non-commercial. It says you may only copy for your own personal use, and only if that personal use is also non-commercial... Just saying...

**Comment by benoit74** [comment] 2024-06-21 06:24
@RavanJAltaie why did you started again the recipe yesterday despite all that has been said here? I cancelled it again

**Comment by RavanJAltaie** [comment] 2024-06-21 13:56
@benoit74 apologies, I did that before checking the issue and comments here.
Well noted.

**Comment by Popolechien** [comment] 2024-06-26 09:04
Based on @Jaifroid 's comment above re:coypright & licensing, shouldn't this request be closed as `invalid` ?

**Comment by RavanJAltaie** [comment] 2024-06-26 13:56
> Based on @Jaifroid 's comment above re:coypright & licensing, shouldn't this request be closed as `invalid` ?

I agree, issue tagged as invalid and closed.
Recipe Deleted.

**Closed by RavanJAltaie** 2024-06-26 13:56 UTC
Labels: Invalid, Zimit, Computer Science

**Comment by benoit74** [comment] 2024-06-27 07:14
> Based on @Jaifroid 's comment above re:coypright & licensing, shouldn't this request be closed as invalid ?

Shouldn't we at least try contact Microsoft to have their permission? Microsoft being who they are, this website is a very important source of documentation / knowledge for the "computing" communities. Not sure it will be easy to have a consent from them, but at least the license is quite clear that it should be possible.

**Comment by Popolechien** [comment] 2024-06-27 07:16
Note a bad idea but that would be business dev and probably a separate discussion. We'll revive the ticket if/when we find someone to talk to (the company is huge so we'd probably have to worm our way through their internal foodchain).
