### ISSUE TITLE
The Codeless code

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#1167] opened 2024-09-27 12:34 UTC
- Website URL: thecodelesscode.com
- License: **Creative Commons**
- Desired ZIM Title: **The Codeless Code**
- Desired ZIM Description: **An illustrated collection of Art and Philosophy of software development**
- Desired ZIM Icon –png (URL or attach one): n/a
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

I see that the recipe already exists at https://farm.openzim.org/recipes/thecodelesscode.com_en_all/edit and ran successfully, but the zim isn't available on .dev 

@benoit74 could it have been deleted when you cleaned up the repository?

**Comment by benoit74** [comment] 2024-09-27 17:42
It is available in dev: https://dev.library.kiwix.org/#lang=&q=illustrated+collection, and this is a duplicate of https://github.com/openzim/zim-requests/issues/1083

**Closed by benoit74** 2024-09-27 17:42 UTC
