### ISSUE TITLE
New  request: pokemon.fandom.com

### ISSUE THREAD

**Issue by uriesk** [openzim/zim-requests#545] opened 2023-01-05 16:27 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

Website URL: https://pokemon.fandom.com/
License: CC BY-NC-SA 3.0
Desired ZIM Title: Pokemon Wiki
Desired ZIM Description: The Pokémon Wiki is a wiki - a web-based encyclopedia - for the Pokémon franchise, a media franchise owned by Nintendo
Desired ZIM Icon –png (URL or attach one): [icon.png](https://static.wikia.nocookie.net/pokemon/images/e/e6/Site-logo.png/revision/latest?cb=20220828185411)
Language (ISO 639-3): eng
Desired Main Page (homepage, if different from website URL): n/a
Is this a MediaWiki?: yes

**Comment by kelson42** [comment] 2023-01-05 16:54
I will try it

**Comment by Agetian** [comment] 2023-01-05 17:02
Sounds like a great replacement for Bulbagarden if it works! :+1:

**Comment by kelson42** [comment] 2023-01-05 20:56
Done https://farm.openzim.org/recipes/pokemon_fandom_en_all

**Comment by Agetian** [comment] 2023-01-06 04:33
Hmm, this looks to be failing with 503 on visualeditor as well, judging by the debug output - is it the same as Bulbapedia then when it comes to restricting access to making offline snapshots?.. :/

**Comment by kelson42** [comment] 2023-01-06 05:23
@Agetian Problem is Fandom backend failing to deliver a long article (title "substitute"). If this is only one or two we might add exception, or article might be splitted in the wiki.

**Comment by uriesk** [comment] 2023-01-06 20:14
i tested it locally and those were the articles that i had to ignore to make it work:
```
--articleListToIgnore "Substitute,Iron Tail,Taunt,Iron Defense,Endure"
```

**Comment by RavanJAltaie** [comment] 2023-01-10 22:00
Recipe Created
https://pokemon.fandom.com/wiki/Pok%C3%A9mon_Wiki

**Comment by kelson42** [comment] 2023-01-11 05:43
@RavanJAltaie Recipe was already created and ticket was assigned to me!?

**Comment by RavanJAltaie** [comment] 2023-01-11 05:56
No, I didn't assign it to you, I'm reviewing if it successfully done or not then will close it.

**Comment by kelson42** [comment] 2023-01-11 06:02
I assigned the ticket to me a few days ago. That means intake care. What I did, i already had created the recipe days ago and it is failing. Solving the problem is ongoing.

**Comment by RavanJAltaie** [comment] 2023-07-05 08:39
@kelson42 Any update on this please?

**Comment by benoit74** [comment] 2023-11-06 21:15
Looks like the list of articles to ignore is no more accurate. Working on it locally for greater flexibility.

**Comment by benoit74** [comment] 2023-11-07 17:05
List of articles to ignore seems to be ok now, running again [on the farm](https://farm.openzim.org/pipeline/5efd14e8-ad91-4826-904b-fd93651d26b7)

**Comment by benoit74** [comment] 2023-11-09 07:04
Finally achieved to get a ZIM which looks not pretty good in terms of content : https://dev.library.kiwix.org/viewer#pokemonwiki_en_all_maxi_2023-11

UI styles have however not been captured at all, @kelson42 @VadimKovalenkoSNF is there something we can do on this? Recipe on the farm is here: https://farm.openzim.org/recipes/pokemon_fandom_en_all/config

I had to ignore a bunch of articles which were failing to get retrieved: https://drive.farm.openzim.org/pokemon_fandom_en_all/pokemon_fandom_en_all_articleListToIgnore.txt

@Popolechien @RavanJAltaie could you please check the ZIM quality according to your standards? Plus confirm configuration is OK (typically I'm not sure the monthly periodicity makes any sense for such a content, don't know what are your guidelines on this topic).

**Comment by Popolechien** [comment] 2023-11-09 10:13
I don't think we have any periodicity criteria. My hunch would be to check special:recentchanges and based on that decide whether there's enough movement in a month to warrant an update.

**Comment by RavanJAltaie** [comment] 2023-11-15 13:13
Recipe succeeded, link of file in Library
https://library.kiwix.org/viewer#pokemonwiki_en_all_maxi_2023-11

**Closed by RavanJAltaie** 2023-11-15 13:13 UTC
Labels: In Progress, Entertainment
