### ISSUE TITLE
New request: PsychonautWiki

### ISSUE THREAD

**Issue by zwass** [openzim/zim-requests#1084] opened 2024-06-28 06:17 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://PsychonautWiki.org
- License: Creative Commons Attribution-ShareAlike 4.0 International
- Desired ZIM Title: PsychonautWiki
- Desired ZIM Description: PsychonautWiki is a community-driven online encyclopedia that aims to document the emerging field of psychonautics in a comprehensive, scientifically-grounded manner
- Desired ZIM Icon –png (URL or attach one): https://m.psychonautwiki.org/wiki/File:Psychonautwiki_hires.png
- Language (ISO 639-3): english
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment] 2024-06-28 08:27
Duplicate of #634 (which apparently was met with a bug) :-/

**Closed by Popolechien** 2024-06-28 08:27 UTC
