### ISSUE TITLE
Missing articles in wikipedia_en_all_nopic_2019-10.zim

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#212] opened 2019-12-12 15:35 UTC
For some reason the latest nopic iteration of the English Wikipedia seems to be missing a few of the Finish presidents, e.g. Mauno Koivisto, Martti Ahtisaari, and Tarja Halonen. All these articles have been around for a while, though.

**Comment by kelson42** [comment] 2019-12-12 15:38
@Popolechien Caused by https://github.com/openzim/mwoffliner/issues/993.

**Comment by kelson42** [comment] 2020-04-18 07:52
This is a duplicate of https://github.com/openzim/mwoffliner/issues/993

**Closed by kelson42** 2020-04-18 07:52 UTC
Labels: bug
