### ISSUE TITLE
Explain XKCD

### ISSUE THREAD

**Issue by Popolechien** [openzim/zim-requests#269] opened 2020-05-27 11:39 UTC
- Website URL: https://www.explainxkcd.com/
- License: CC-by-sa
- Desired ZIM Title: Explain XKCD
- Desired ZIM Description: "It's 'cause you're dumb"
- Desired ZIM Icon –png (URL or attach one): http://www.userlogos.org/files/logos/euphonicnight/XKCDw.png
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: Yes

**Comment by kelson42** [comment] 2020-12-30 07:03
Done https://farm.openzim.org/recipes/expain-xkcd

**Comment by rgaudin** [comment] 2020-12-30 09:01
There is is no ZIM and probably an mwoffliner bug (exit-status of `0` without a zim).

**Comment by rgaudin** [comment] 2020-12-30 09:01
Recipe link: https://farm.openzim.org/recipes/explain-xkcd
Current last run: https://farm.openzim.org/pipeline/997668a222568d3e1362cef5

**Comment by kelson42** [comment] 2020-12-30 09:25
Duplicate of https://github.com/openzim/mwoffliner/issues/1350, Not sure what happens exactly for now, but should not be a big deal. Most probably a wrong configuration coupled with a bad exception handling at MWoffliner.

**Closed by kelson42** 2020-12-30 09:25 UTC
Labels: mediawiki
