### ISSUE TITLE
New ZIM request: Zimit doesnt work for Inciclopedia, help pls

### ISSUE THREAD

**Issue by MetalicusJarcor** [openzim/zim-requests#404] opened 2021-12-13 04:34 UTC
- Website URL: https://inciclopedia.org/
- License: Creative Commons Attribution Share Alike
- Desired ZIM Title: Inciclopedia
- Desired ZIM Icon –png (URL or attach one): https://images.uncyclomedia.co/inciclopedia/es/c/c4/Incilogo_anim.gif
- Language (ISO 639-3): esp
- Is this a MediaWiki?: yes

**Comment by Popolechien** [comment] 2021-12-13 11:57
@kelson42 [we have the recipe already](https://farm.openzim.org/recipes/inciclopedia_es_all) but fails (I suspect because of known mwoffliner issues). Should we move the ticket, keep it here, or close it a `duplicate`?

**Comment by kelson42** [comment] 2021-12-13 11:59
Without precise details about what is exactly wrong, I would close it.

**Comment by Popolechien** [comment] 2021-12-13 12:19
Over the last three runs we had twice `mwUrl [https://inciclopedia.org] is not valid.`
and once 
`Failed to run mwoffliner after [603s]: {`
`	"code": "apierror-visualeditor-docserver-http-error",`
`	"info": "(curl error: 52) Server returned nothing (no headers, no data)",`

**Closed by Popolechien** 2021-12-13 12:19 UTC
Labels: bug

**Comment by Popolechien** [comment] 2021-12-13 12:20
@MetalicusJarcor To be clear it is not that we ignore your issue, but simply that the problem is bigger than this particular website and will be dealt with elsewhere.

**Comment by MetalicusJarcor** [comment] 2021-12-13 14:14
@Popolechien No problem, thank you for your time.
