### ISSUE TITLE
Koch-Wiki ZIMs are broken

### ISSUE THREAD

**Issue by chjohn22** [openzim/zim-requests#324] opened 2021-02-04 19:47 UTC
All ZIMs from Koch-Wiki are broken since last autumn. They had a size of about 40-50 Megabytes each, but now they only weigh 4-5 Megabytes. So all new versions which are available for download are totally broken. Each article just shows: `[object Object]`

Maybe you can publish an old one in working condition until a fix is available? I could send you `kochwiki_de_all_maxi_2020-07.zim`if you do not have it anymore.

**Comment by kelson42** [comment] 2021-02-05 11:05
@chjohn22 Thank you for your bug report, I believe this ticket to be a duplicate of https://github.com/openzim/mwoffliner/issues/1363. Therefore, closing.

**Closed by kelson42** 2021-02-05 11:05 UTC
Labels: bug, duplicate

**Comment by kelson42** [comment] 2021-02-05 12:34
New *proper* ZIM files should be available online in the next hours, see https://farm.openzim.org/pipeline/976994088c589d106213d106
