### ISSUE TITLE
openstax Textbooks 

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#73] opened 2018-09-18 10:07 UTC
_From @amirh123123 on March 12, 2018 5:57_

hi please make zim file for openstax Textbooks 

_Copied from original issue: openzim/mwoffliner#233_

**Comment by kelson42** [comment] 2018-09-18 10:07
URL please?

**Comment by kelson42** [comment] 2018-09-18 10:07
_From @amirh123123 on March 12, 2018 11:19_

http://dev.worldpossible.org/cgi/viewmod.pl?module_id=116

**Comment by Popolechien** [comment] 2020-02-24 15:44
duplicate of #136

**Closed by Popolechien** 2020-02-24 15:44 UTC
Labels: ZIM, duplicate
