### ISSUE TITLE
New  request: marxists.org collection

### ISSUE THREAD

**Issue by jmthackett** [openzim/zim-requests#594] opened 2023-04-02 19:05 UTC
- Website URL: https://marxists.org
- License: **Creative Commons (CC-SA) + Public domain ** - See: https://www.marxists.org/admin/janitor/faq.htm#copyright
- Desired ZIM Title: Marxism
- Desired ZIM Description: The collected works of Marx and Marxists from around the world.
- Desired ZIM Icon –png (URL or attach one): https://www.marxists.org/glossary/people/m/pics/marx.jpg
- Language (ISO 639-3): **eng** [Mainly english, but: https://www.marxists.org/ lists a number of languages]
- Is this a MediaWiki?: **no**

**Comment by tim78245** [comment] 2023-05-14 17:04
The entire website is around a terabyte and the MIA has consistently asked people not to scrape the site, as they are almost always close to using their maximum monthly bandwidth. Ignoring pdfs makes it more manageable.

The typical way the zimfarm scrapes these sorts of things (into a warc file then replaying the warc file) would be inferior to just wgeting it, as it is a simple site with all links relative already.

I would probably do something like:

wget -Ekpxr -R pdf,mp3,epub,zip marxists.architexturez.net

and then use a script to remove all links to pdf files and then use zimwriterfs.

You may also wish to communicate this to the MIA (I believe they have a facebook page). They may end up making their own, they could host their zims on a site like archive.org to reduce their own bandwidth.

**Comment by benoit74** [comment] 2024-06-17 13:33
Isn't this a duplicate of https://github.com/openzim/zim-requests/issues/311? We could close this one, isn't it?

**Comment by benoit74** [comment] 2024-10-24 20:24
Closing as duplicate of #311

**Closed by benoit74** 2024-10-24 20:24 UTC
Labels: Zimit, General Information
