### ISSUE TITLE
Make a zim of Appropedia.org

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-requests#5] opened 2018-09-18 09:37 UTC
_From @Popolechien on September 4, 2018 5:56_

Address is http://www.appropedia.org/ and the site is under CC-by-SA

_Copied from original issue: openzim/mwoffliner#371_

**Comment by Popolechien** [comment] 2019-10-01 07:11
Duplicate of #190

**Closed by Popolechien** 2019-10-01 07:11 UTC
Labels: ZIM, duplicate, mediawiki
