### ISSUE TITLE
New  request: Free Software Directory

### ISSUE THREAD

**Issue by ToeushiMWYKaesai** [openzim/zim-requests#581] opened 2023-03-20 23:27 UTC
- Website URL: https://directory.fsf.org
- License: **[GFDL](https://static.fsf.org/nosvn/directory/fdl-1.3-standalone.html)** 
- Desired ZIM Title: **Free Software Directory**
- Desired ZIM Description: **Directory of Free Software**
- Desired ZIM Icon –png (URL or attach one): https://directory.fsf.org/favicon.ico
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **yes**

**Comment by tim78245** [comment] 2023-05-14 17:05
duplicate #473

**Comment by RavanJAltaie** [comment] 2024-05-28 22:42
Duplicate of #473

**Closed by RavanJAltaie** 2024-05-28 22:42 UTC
Labels: Mediawiki, Computer Science
