### ISSUE TITLE
Wookieepedia.com

### ISSUE THREAD

**Issue by iiamdillon** [openzim/zim-requests#518] opened 2022-11-25 15:13 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://starwars.fandom.com/wiki/Main_Page
- License: Public domain
- Desired ZIM Title: **Wookieepedia*
- Desired ZIM Description: **The definitive Star Wars guide.**
- Desired ZIM Icon –png (URL or attach one): https://static.wikia.nocookie.net/starwars/images/e/e6/Site-logo.png/revision/latest?cb=20210602103636
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by Popolechien** [comment] 2022-11-25 15:16
Duplicate of #375, #478. Wookies sure are popular.

**Comment by iiamdillon** [comment] 2022-11-25 15:17
> Duplicate of #375, #478. Wookies sure are popular.

My bad. I'm really wanting an offline Wookieepedia though ahah

**Closed by Popolechien** 2022-11-25 15:16 UTC
Labels: duplicate
