### ISSUE TITLE
New request: pressbooks.pub/harmonyandmusicianshipwithsolfege/

### ISSUE THREAD

**Issue by Rexadev** [openzim/zim-requests#1053] opened 2024-06-15 18:50 UTC
- Website URL: https://pressbooks.pub/harmonyandmusicianshipwithsolfege/
- License: 
- Desired ZIM Title: Harmony and Musicianship with Solfège by Laszlo Cser and Daniel Wanner (pressbooks.pub)
- Desired ZIM Description: The textbook adheres to the harmony and musicianship course requirements of college music programs, presenting comprehensive harmony studies and assignments of the Common Practice Period (1600-1900), sight singing and ear training materials, and chapters introducing 20th century music techniques including jazz.
- Desired ZIM Icon –png (URL or attach one): 
![image](https://github.com/openzim/zim-requests/assets/62152714/76875053-7301-43e8-a5bb-9d550e888157)
- Language (ISO 639-3): **eng**
- Is this a MediaWiki?: **no**

**Comment by RavanJAltaie** [comment] 2024-06-23 19:28
LICENSE:
Copyright © 2022 by Laszlo Cser and Daniel Wanner. All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form or by any means without the prior written permission of the authors.

Closing the issue due to copyright license.

**Closed by RavanJAltaie** 2024-06-23 19:28 UTC
