### ISSUE TITLE
New  request: en.uesp.net

### ISSUE THREAD

**Issue by wolfweim** [openzim/zim-requests#630] opened 2023-05-02 21:04 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://en.uesp.net/
- License: Attribution-ShareAlike 2.5 License
- Desired ZIM Title: En_Uesp.zim
- Desired ZIM Description: "A collaborative source for all knowledge on the Elder Scrolls series since 1995"
- Desired ZIM Icon –png (URL or attach one): https://en.uesp.net/favicon.ico
- Language (ISO 639-3): eng
- Is this a MediaWiki?: Yes

**Comment by Popolechien** [comment] 2024-07-21 18:13
duplicate of #595

**Closed by Popolechien** 2024-07-21 18:13 UTC
Labels: Duplicate, Mediawiki, General Information
