### ISSUE TITLE
Wiktionary translations missing

### ISSUE THREAD

**Issue by ynikitenko** [openzim/zim-requests#253] opened 2020-04-24 13:02 UTC
Recent wiktionary (full English wiktionary from 2020-01-17) has no translations (I can't open them using several versions of Kiwix-desktop, including the last one 2.0.1).
There is a section with translations on article pages, but no translations are present there.

**Comment by kelson42** [comment] 2020-04-27 15:34
Duplicate of https://github.com/openzim/mwoffliner/issues/1033

**Closed by kelson42** 2020-04-27 15:34 UTC
