### ISSUE TITLE
Errors in the ZIM archive description 

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/zim-requests#266] opened 2020-05-26 07:46 UTC
Open file **wikipedia_ru_computer_maxi_2020-01.zim** in **Kiwix**:
![Kiwix-comp-ru](https://user-images.githubusercontent.com/65112331/82873363-10afce80-9f3d-11ea-867c-abcc57860a94.png)

This is a grammatically **incorrect** sentence:

> Компьютер Википедии

Here is the **correct** sentence:
> Википедия Информатика

This is a grammatically **incorrect** sentence:

> Подборка статей Википедии на компьютере

Here is the **correct** sentence:
> Подборка статей из Википедии по информатике

**Comment by Popolechien** [comment] 2020-05-26 09:06
@Ubuntu-2020 I can't tell if the issue is on the zim or desktop environment, but if the latter then you can help translating it here:
https://translatewiki.net/w/i.php?title=Special:Translate&group=kiwix-desktop&language=ru&filter=&action=translate

I will look into the zim itself

**Comment by Popolechien** [comment] 2020-05-26 09:07
Ok I edited the zimfarm recipe 
https://farm.openzim.org/recipes/wikipedia_ru_computer/config
Should be fixed with the next run

**Closed by Popolechien** 2020-05-26 09:07 UTC
