### ISSUE TITLE
mineraft wiki

### ISSUE THREAD

**Issue by fuefbre55gr** [openzim/zim-requests#726] opened 2023-10-06 15:22 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://minecraft.wiki/
- License: **Creative Commons | Public domain | ...**
- Desired ZIM Title: **minecraft wiki**
- Desired ZIM Description: **minecraft wiki-october 2023**
- Is this a MediaWiki?: **yes**

**Comment by Popolechien** [comment] 2023-10-06 15:25
duplicate of #710

**Closed by Popolechien** 2023-10-06 15:25 UTC
Labels: Duplicate
