### ISSUE TITLE
New request: Bulbapedia 2024

### ISSUE THREAD

**Issue by mcsquared789** [openzim/zim-requests#931] opened 2024-03-22 20:57 UTC
- Website URL: https://bulbapedia.bulbagarden.net
- License: Creative Commons (Attribution-NonCommercial-ShareAlike 2.5 Generic)
- Desired ZIM Title: Bulbapedia
- Desired ZIM Description: From Bulbapedia, the community-driven Pokémon encyclopedia. (Updated for 2024)
- Desired ZIM Icon –png (URL or attach one): https://archives.bulbagarden.net/media/upload/2/25/Bulbapedia_logo.png
- Language (ISO 639-3): eng
- Is this a MediaWiki?: yes

**Comment by kelson42** [comment] 2024-03-23 13:22
Duplicate of #783

**Closed by kelson42** 2024-03-23 13:22 UTC
