### ISSUE TITLE
New ZIM request: Wookieepedia

### ISSUE THREAD

**Issue by DaveAlton** [openzim/zim-requests#478] opened 2022-09-17 04:33 UTC
*Please use the following format for a ZIM creation request (and delete unnecessary information)*

- Website URL: https://starwars.fandom.com/wiki/Main_Page
- License: **CC-by-sa | Public domain | ...** (do NOT request copyrighted material)
- Desired ZIM Title: **Wookieepedia**
- Desired ZIM Description: ** Wookieepedia is a wiki-based online encyclopedia that contains detailed information about the Star Wars universe, including movies, books, video games, characters, locations, technology, weapons, vehicles, and everything in between.**
- Desired ZIM Icon –png (URL or attach one): https://kids.kiddle.co/images/7/71/WookieepediaLogoEng.png
- Language (ISO 639-3): **eng**
- Desired Main Page (homepage, if different from website URL): **n/a**
- Is this a MediaWiki?: **yes**

**Comment by tim78245** [comment] 2022-09-18 19:03
Duplicate of #375 
Looking at the last couple of logs:
https://farm.openzim.org/pipeline/b48c2f1d570c26d1554b1236/debug
https://s3.us-west-1.wasabisys.com/org-kiwix-zimfarm-logs/3016143aaef79973cc7c8f26_mwoffliner.log
It appears to me Wookieepedia is really large and fandom's API eventually fails with a 503, leading the entire job to quit. Sometimes I can get around such an error simply by retrying a few times, but I think mwoffliner will have to be updated with a sort of 'retry article later' handler.

**Comment by Popolechien** [comment] 2022-11-25 15:16
Forgot to close this one (recipe has been created, zim will eventually be made) but yeah, Tim's assessment is correct.

**Closed by Popolechien** 2022-11-25 15:16 UTC

**Comment by iiamdillon** [comment] 2022-11-25 15:19
> Forgot to close this one (recipe has been created, zim will eventually be made) but yeah, Tim's assessment is correct.

How long do you think it will be till Wookieepedia zim is created?

**Comment by Popolechien** [comment] 2022-11-25 15:20
@iiamdillon No, the recipe on the zimfarm has but it is currently failing. We are however likely to use Wookieepdia as reference (or test case) for the revamp work that is about to start.

**Comment by Popolechien** [comment] 2022-11-25 15:22
We have no stronger wish.
