### ISSUE TITLE
New request: NixOS unofficial wiki

### ISSUE THREAD

**Issue by gtespe** [openzim/zim-requests#808] opened 2024-01-31 05:52 UTC
- Website URL: https://nixos.wiki/
- License: MIT
- Desired ZIM Title: NixOS Wiki
- Desired ZIM Description: The NixOS unofficial user's wiki
- Desired ZIM Icon –png (URL or attach one): https://nixos.wiki/nixos-logo-small.png
- Language (ISO 639-3): eng
- Is this a MediaWiki?: no

**Comment by benoit74** [comment] 2024-02-01 13:57
Duplicate of #636

**Closed by benoit74** 2024-02-01 13:57 UTC
