### ISSUE TITLE
New ZIM request: arch linux portugues

### ISSUE THREAD

**Issue by outusuke** [openzim/zim-requests#306] opened 2020-11-08 01:42 UTC
- Website URL: wiki.archlinux.org
- License: gnu
- Desired ZIM Title: archlinux_pt-br_all_maxi
- Desired ZIM Description: documentação do Arch Linux
- Desired ZIM Icon: https://upload.wikimedia.org/wikipedia/commons/a/a5/Archlinux-icon-crystal-64.svg
- Language (ISO 639-3): pt-br
- Desired Main Page https://wiki.archlinux.org/index.php/Main_page_(Português)

**Comment by kelson42** [comment] 2021-01-17 09:30
Duplicate of https://farm.openzim.org/recipes/archlinux_wiki

**Closed by kelson42** 2021-01-17 09:30 UTC
Labels: mediawiki

**Comment by outusuke** [comment] 2021-01-17 12:03
this is not a duplicate, it is the arch linux version in Portuguese

**Comment by outusuke** [comment] 2021-01-17 12:06
I believe it is not a duplicate, because it is the Portuguese version

**Comment by kelson42** [comment] 2021-01-17 14:22
same wiki, multilinguale, http://library.kiwix.org/archlinux_en_all_maxi_2021-01/A/Main_page_(Portugu%C3%AAs)

**Comment by outusuke** [comment] 2021-01-17 16:27
> same wiki, multilinguale, http://library.kiwix.org/archlinux_en_all_maxi_2021-01/A/Main_page_(Portugu%C3%AAs)

yes, i saw it later so i deleted the previous message.
